### ISSUE TITLE
No inicia activspire

### ISSUE THREAD

**Issue by Poyuo** [aosucas499/activdre#2]
Hola! Primero agradecerte lo que has hecho. Te hablo desde Almeria, mi nombre es Iván, estamos intentando instalar guadalinex plus, pero al instalar la aplicación de promethean y tras darle al permiso de lanzar y tras reiniciar no me abre la aplicación, no sabemos que hacemos mal, hemos probado en diferentes equipos, hemos dejado incluso a que actualice pero no conseguimos que cargue el icono de  calibrar pdi (el que se pone arriba la derecha) ni que abra la aplicación activinspire, que puede ser que esté pasando? Será necesario que agrede alguna dirección en gesuser en la lista blanca? En tal caso que direcciones añado? Gracias por tu colaboración

**Comment by aosucas499** [comment]
Hola Iván.
Este proyecto donde me escribes es el proyecto para instalar las drivers de las pizarras promethean en cualquier sistema linux.
El proyecto educaandos +, lo tienes [aquí.](https://github.com/aosucas499/guadalinex)
Ese problema del que me hablas es por una actualización que proviene del sistema oficial. Las soluciones son dos:

1. Sigues este tutorial antes de instalar las pizarras: [enlace ](https://drive.google.com/file/d/1NvGVTt54kdUEgO94fCKkBoWLluVpZhyY/view?usp=sharing)
2. Esperas que en breve habrá una nueva iso con todo resuelto y desde el que podrás instalar las pizarras promethean.
